"""Add foreign key constraint to submissions.template_id

Revision ID: 14ecaa84cb86
Revises: 25368d9dcc5f
Create Date: 2025-12-04 20:55:11.310364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ecaa84cb86'
down_revision: Union[str, Sequence[str], None] = '25368d9dcc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'submissions', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    # ### end Alembic commands ###
